'use client';
import { AntdRegistry } from '@ant-design/nextjs-registry';
// import '@ant-design/v5-patch-for-react-19';
import { ConfigProvider } from 'antd';
import React from 'react';

const AntDesignProvider = ({ children }: React.PropsWithChildren) => {
  return (
    <AntdRegistry>
      <ConfigProvider
        prefixCls="dd"
        theme={{
          cssVar: {},
          token: {
            // global token
            fontFamily: 'var(--font-geist-sans)',
            colorPrimary: 'var(--color-dd-primary-500)',
            lineHeight: 1,
            borderRadius: 8,
            fontSize: 16,
            colorBgContainer: 'var(--color-white)',
            colorBgContainerDisabled: 'var(--color-dd-gray-100)',
            colorBgSolid: 'var(--color-dd-gray-950)',
            controlHeight: 40,
            controlHeightLG: 48,
            controlHeightSM: 32,
            colorBorder: 'var(--color-dd-gray-300)',
            colorLink: 'var(--color-dd-primary-500)',
            colorText: 'var(--color-dd-gray-900)',
            colorTextDisabled: 'var(--color-dd-gray-400)',
            colorTextDescription: 'var(--color-dd-gray-500)',
            colorBorderSecondary: 'var(--color-dd-gray-200)',
            colorBgTextHover: 'var(--color-dd-primary-100)',
            colorTextPlaceholder: 'var(--color-dd-gray-500)',
          },
          components: {
            Layout: {
              bodyBg: 'var(--color-white)',
              footerBg: 'var(--color-dd-gray-50)',
              footerPadding: '24px 50px',

              headerBg: 'var(--color-dd-primary-500)',
              headerColor: 'var(--color-white)',
              headerHeight: 64,
              headerPadding: '0 50px',

              lightSiderBg: 'var(--color-white)',
              lightTriggerBg: 'var(--color-dd-gray-100)',
              lightTriggerColor: 'var(--color-dd-gray-900)',

              siderBg: 'var(--color-dd-primary-50)',
              triggerBg: 'var(--color-dd-primary-600)',
              triggerColor: 'var(--color-white)',
              triggerHeight: 48,

              zeroTriggerHeight: 40,
              zeroTriggerWidth: 40,
            },
            Menu: {
              activeBarBorderWidth: 2,
              activeBarHeight: 2,
              activeBarWidth: 0,
              collapsedIconSize: 16,
              collapsedWidth: 80,

              // Danger states
              dangerItemActiveBg: 'var(--color-dd-red-50)',
              dangerItemColor: 'var(--color-dd-red-500)',
              dangerItemHoverColor: 'var(--color-dd-red-600)',
              dangerItemSelectedBg: 'var(--color-dd-red-50)',
              dangerItemSelectedColor: 'var(--color-dd-red-600)',

              // Popup
              dropdownWidth: 160,
              popupBg: 'var(--color-white)',
              zIndexPopup: 1050,

              // Group title
              groupTitleColor: 'var(--color-dd-gray-500)',
              groupTitleFontSize: 14,
              groupTitleLineHeight: 1.6,

              // Horizontal menus
              horizontalItemBorderRadius: 6,
              horizontalItemHoverBg: 'transparent',
              horizontalItemHoverColor: 'var(--color-dd-primary-500)',
              horizontalItemSelectedBg: 'transparent',
              horizontalItemSelectedColor: 'var(--color-dd-primary-600)',
              horizontalLineHeight: '46px',

              // Icons
              iconMarginInlineEnd: 10,
              iconSize: 16,

              // Items
              itemActiveBg: 'var(--color-dd-primary-500)',
              itemBg: 'var(--color-dd-primary-50)',
              itemBorderRadius: 8,
              itemColor: 'var(--color-dd-gray-900)',
              itemDisabledColor: 'var(--color-dd-gray-400)',
              itemHeight: 40,
              itemHoverBg: 'var(--color-dd-primary-100)',
              itemHoverColor: 'var(--color-dd-gray-900)',
              itemMarginBlock: 4,
              itemMarginInline: 4,
              itemPaddingInline: 16,
              itemSelectedBg: 'var(--color-dd-primary-500)',
              itemSelectedColor: 'var(--color-white)',
            },
            Button: {
              // primary button
              colorPrimaryText: 'var(--color-white)',
              colorPrimary: 'var(--color-dd-primary-500)',
              colorPrimaryHover: 'var(--color-dd-primary-600)',
              primaryShadow: 'var(--shadow-dd-xs)',
              colorPrimaryActive: 'var(--color-dd-primary-600)',
              colorPrimaryBorder: 'var(--color-dd-primary-500)',
              colorPrimaryBorderHover: 'var(--color-dd-primary-600)',
              fontWeight: 600,

              // default button
              defaultBorderColor: 'var(--color-dd-gray-300)',
              defaultShadow: 'var(--shadow-dd-xs)',
              defaultActiveBg: 'var(--color-dd-primary-50)',
              defaultActiveBorderColor: 'var(--color-dd-primary-500)',

              // for all buttons
              contentFontSize: 16,
              borderColorDisabled: 'var(--color-dd-gray-200)',
            },
            Input: {
              activeBorderColor: 'var(--color-dd-primary-500)',
              activeBg: 'var(--color-white)',
              activeShadow: 'var(--shadow-dd-ring-xs)',
              addonBg: 'var(--color-dd-gray-100)',
              hoverBg: 'var(--color-white)',
              hoverBorderColor: 'var(--color-dd-primary-500)',
              inputFontSize: 16,
              paddingBlock: 8,
              paddingInline: 12,
              colorTextPlaceholder: 'var(--color-dd-gray-500)',
              lineHeight: 1,
            },
            InputNumber: {
              activeBorderColor: 'var(--color-dd-primary-500)',
              activeBg: 'var(--color-white)',
              activeShadow: 'var(--shadow-dd-ring-xs)',
              hoverBg: 'var(--color-white)',
              hoverBorderColor: 'var(--color-dd-primary-500)',
              inputFontSize: 16,
              paddingBlock: 8,
              paddingInline: 12,
              colorTextPlaceholder: 'var(--color-dd-gray-500)',
              lineHeight: 1,
            },
            Pagination: {
              itemActiveBg: 'var(--color-dd-primary-500)',
              itemSize: 35,
              itemBg: 'var(--color-dd-gray-200)',
              colorText: 'var(--color-dd-gray-900)',
            },
            Select: {
              activeBorderColor: 'var(--color-dd-primary-500)',
              activeOutlineColor: 'var(--shadow-dd-ring-xs)',
              hoverBorderColor: 'var(--color-dd-primary-500)',
              clearBg: 'var(--color-white)',
              selectorBg: 'var(--color-white)',
              optionActiveBg: 'var(--color-dd-primary-50)',
              optionSelectedBg: 'var(--color-dd-primary-50)',
              optionSelectedColor: 'var(--color-dd-primary-500)',
              optionSelectedFontWeight: 600,
              optionFontSize: 16,
              optionHeight: 40,
              optionPadding: '8px 12px',
              multipleItemBg: 'var(--color-dd-primary-50)',
              multipleItemBorderColor: 'var(--color-dd-primary-200)',
              multipleItemHeight: 28,
              multipleItemHeightLG: 32,
              multipleItemHeightSM: 24,
              multipleSelectorBgDisabled: 'var(--color-dd-gray-100)',
              multipleItemColorDisabled: 'var(--color-dd-gray-400)',
              multipleItemBorderColorDisabled: 'var(--color-dd-gray-200)',
              singleItemHeightLG: 48,
              showArrowPaddingInlineEnd: 12,
            },
            Tabs: {
              inkBarColor: 'var(--color-dd-primary-500)',
              itemActiveColor: 'var(--color-dd-primary-500)',
              itemColor: 'var(--color-dd-gray-500)',
              itemHoverColor: 'var(--color-dd-primary-500)',
              itemSelectedColor: 'var(--color-dd-primary-500)',
              horizontalItemGutter: 16,

              // card tabs
              cardBg: 'transparent',
              cardHeight: 20,
              cardPadding: '8px 12px',
              colorBorderSecondary: 'transparent',
              colorBgContainer: 'var(--color-dd-primary-50)',
            },
            DatePicker: {
              activeBg: 'var(--color-white)',
              activeBorderColor: 'var(--color-dd-primary-500)',
              activeShadow: 'var(--shadow-dd-xs)',
              addonBg: 'var(--color-dd-primary-500)',
              cellActiveWithRangeBg: 'var(--color-dd-primary-500)',
              cellBgDisabled: 'var(--color-dd-gray-200)',
              cellHoverBg: 'var(--color-dd-primary-50)',
              cellWidth: 40,
              hoverBg: 'var(--color-white)',
              hoverBorderColor: 'var(--color-dd-primary-500)',
              paddingBlock: 8,
              paddingInline: 12,
            },
            Table: {
              borderColor: 'var(--color-dd-gray-200)',
              cellFontSize: 18,
              headerBg: 'var(--color-white)',
              headerBorderRadius: 10,
              headerColor: 'var(--color-dd-gray-750)',
              rowHoverBg: 'var(--color-dd-gray-50)',
            },
            Tag: {
              defaultBg: 'var(--color-white)',
              defaultColor: 'var(--color-dd-gray-800)',
            },
            Dropdown: {
              fontSizeIcon: 18,
              fontSizeSM: 18,
              colorBgElevated: 'var(--color-white)',
              controlItemBgHover: 'var(--color-dd-primary-50)',
            },
            Divider: {
              colorSplit: 'var(--color-dd-gray-200)',
            },
            Form: {
              labelColor: 'var(--color-dd-gray-950)',
            },
            Statistic: {
              titleFontSize: 15,
              contentFontSize: 25,
              lineHeight: 1.5,
            },
            Switch: {
              colorPrimary: 'var(--color-dd-primary-500)',
              colorPrimaryHover: 'var(--color-dd-primary-600)',
              colorPrimaryBorder: 'var(--color-dd-primary-500)',
              colorBgContainer: 'var(--color-white)',
              colorTextQuaternary: 'var(--color-dd-gray-400)',
              colorTextTertiary: 'var(--color-dd-gray-500)',
              handleBg: 'var(--color-white)',
              handleShadow: 'var(--shadow-dd-xs)',
              opacityLoading: 0.6,
              trackHeight: 22,
              trackMinWidth: 44,
              trackPadding: 2,
              handleSize: 18,
              innerMaxMargin: 24,
              innerMinMargin: 4,
            },
            Modal: {
              contentBg: 'var(--color-white)',
              headerBg: 'var(--color-white)',
              footerBg: 'var(--color-white)',
              titleColor: 'var(--color-dd-gray-900)',
              titleFontSize: 18,
              titleLineHeight: 1.6,
              borderRadiusLG: 12,
              boxShadowTertiary: 'var(--shadow-dd-xl)',
              paddingLG: 24,
              paddingMD: 20,
              paddingContentHorizontalLG: 24,
              paddingContentVerticalLG: 20,
            },
            Spin: {
              colorPrimary: 'var(--color-dd-primary-500)',
              colorText: 'var(--color-dd-gray-600)',
              dotSize: 20,
              dotSizeLG: 32,
              dotSizeSM: 14,
            },
            Card: {
              colorBgContainer: 'var(--color-white)',
              colorBorderSecondary: 'var(--color-dd-gray-200)',
              colorTextHeading: 'var(--color-dd-gray-900)',
              colorTextDescription: 'var(--color-dd-gray-600)',
              borderRadiusLG: 12,
              boxShadowTertiary: 'var(--shadow-dd-sm)',
              headerBg: 'transparent',
              headerHeight: 56,
              headerHeightSM: 48,
              headerFontSize: 16,
              headerFontSizeSM: 14,
              actionsBg: 'var(--color-dd-gray-50)',
              actionsLiMargin: '12px 0',
              tabsMarginBottom: 16,
              paddingLG: 24,
              paddingSM: 16,
              paddingXS: 12,
            },
            Avatar: {
              colorBgContainer: 'var(--color-dd-gray-100)',
              colorText: 'var(--color-dd-gray-600)',
              colorTextLightSolid: 'var(--color-white)',
              colorTextPlaceholder: 'var(--color-dd-gray-400)',
              borderRadius: 6,
              sizeLG: 40,
              size: 32,
              sizeSM: 24,
              sizeXS: 20,
              fontSize: 14,
              fontSizeLG: 18,
              fontSizeSM: 12,
            },
            Upload: {
              colorPrimary: 'var(--color-dd-primary-500)',
              colorPrimaryHover: 'var(--color-dd-primary-600)',
              colorFillAlter: 'var(--color-dd-gray-50)',
              colorBorder: 'var(--color-dd-gray-300)',
              borderRadius: 8,
              borderRadiusLG: 12,
              paddingLG: 24,
              marginXS: 8,
            },
            Radio: {
              colorPrimary: 'var(--color-dd-primary-500)',
              colorPrimaryHover: 'var(--color-dd-primary-600)',
              colorPrimaryActive: 'var(--color-dd-primary-600)',
              colorBorder: 'var(--color-dd-gray-300)',
              colorBgContainer: 'var(--color-white)',
              colorText: 'var(--color-dd-gray-900)',
              dotSize: 8,
              dotColorDisabled: 'var(--color-dd-gray-300)',
              radioSize: 16,
              wrapperMarginInlineEnd: 8,
            },
            Checkbox: {
              colorPrimary: 'var(--color-dd-primary-500)',
              colorPrimaryHover: 'var(--color-dd-primary-600)',
              colorPrimaryActive: 'var(--color-dd-primary-600)',
              colorBorder: 'var(--color-dd-gray-300)',
              colorBgContainer: 'var(--color-white)',
              colorText: 'var(--color-dd-gray-900)',
              colorWhite: 'var(--color-white)',
              borderRadiusSM: 4,
              size: 16,
              sizeSM: 14,
              lineWidth: 1,
            },
            Tooltip: {
              colorBgSpotlight: 'var(--color-dd-gray-900)',
              colorTextLightSolid: 'var(--color-white)',
              borderRadius: 6,
              boxShadowSecondary: 'var(--shadow-dd-lg)',
              paddingSM: 8,
              paddingXS: 6,
              fontSizeSM: 12,
              zIndexPopup: 1070,
            },
            Badge: {
              colorBgContainer: 'var(--color-dd-red-500)',
              colorBorderBg: 'var(--color-white)',
              colorText: 'var(--color-white)',
              fontSizeSM: 12,
              paddingXS: 6,
              statusSize: 6,
              dotSize: 8,
              textFontSize: 12,
              textFontSizeSM: 12,
              textFontWeight: 'normal',
            },
            Skeleton: {
              gradientToColor: 'var(--color-dd-gray-100)',
              borderRadiusSM: 4,
              borderRadius: 6,
              borderRadiusLG: 8,
              controlHeight: 40,
              controlHeightLG: 48,
              controlHeightSM: 32,
            },
            Typography: {
              colorText: 'var(--color-dd-gray-900)',
              colorTextHeading: 'var(--color-dd-gray-900)',
              colorTextLabel: 'var(--color-dd-gray-700)',
              colorTextDescription: 'var(--color-dd-gray-600)',
              colorTextDisabled: 'var(--color-dd-gray-400)',
              colorLink: 'var(--color-dd-primary-500)',
              colorLinkHover: 'var(--color-dd-primary-600)',
              colorLinkActive: 'var(--color-dd-primary-600)',
              fontFamilyCode:
                'ui-monospace, SFMono-Regular, "SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
              titleMarginTop: '1.2em',
              titleMarginBottom: '0.5em',
            },
          },
        }}
      >
        {children}
      </ConfigProvider>
    </AntdRegistry>
  );
};

export default AntDesignProvider;
